### ISSUE TITLE
Periodically update list of Cloudflare IPs

### ISSUE THREAD

**Issue by tobiasmuehl** [kirsch33/realip#1]
Great plugin!

Do you have a plan on how to keep the IP list up to date?

**Comment by kirsch33** [comment]
Thanks! I want to implement something that will grab the latest versions of these files:

https://www.cloudflare.com/ips-v4
https://www.cloudflare.com/ips-v6

and format appropriately to construct a new preset when the module is provisioned. Not sure how to do that quite yet, but when I get some free time I'll look into it. 

Feel free to open a PR if they become out of date or if you have any ideas about getting what I was mentioning above implemented!

**Comment by tobiasmuehl** [comment]
The two ideas I had:

- Run CI/CD task to download the file and push to the repo daily, but that likely complicates versioning


- Run "cronjob-like" task in Caddy to download the files when booting up and then every x hours/days according to a config setting (personal preference)

**Comment by kirsch33** [comment]
@tobiasmuehl 

the newest commit automatically updates to the latest cloudflare IP ranges thanks to @sarge 

i am currently packaging this commit into the first 'v2.0' release.

if the cloudflare request fails, it falls back to a statically maintained IP list that I will do my best to maintain, but regardless this is  a big step forward. for now, I will close this issue.
