### ISSUE TITLE
How can I downgrade CaddyServer

### ISSUE THREAD

**Issue by OccultWarlock** [kirsch33/realip#13]
I accidentally upgraded my caddyserver to 2.5.2 and I’m not sure how to downgrade back to 2.4.6 with the model added. Any advice?

**Comment by francislavoie** [comment]
"with the model added"? Not sure I understand.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by francislavoie** [comment]
See the xcaddy README, you can specify a tag to build from.
