### ISSUE TITLE
Direct access to server with strict option returns a 500 error: Error reading remote addr

### ISSUE THREAD

**Issue by kyori19** [kirsch33/realip#2]
I want to deny access not from cloudflare, such as direct access by hitting ip address.

## Expected behavior

A server returns 403

## Actual behavior

When I access to the server with curl, the server returns 500 with this error.

```bash
$ curl -kIH "Host: <host name>" https://<server addr>/
HTTP/2 500
server: Caddy
strict-transport-security: max-age=31536000
date: Tue, 22 Dec 2020 07:32:47 GMT
```

```
Error reading remote addr: <my ip addr>:56264
```

## Configuration

```
realip {
  header "X-Forwarded-For"
  from cloudflare
  maxhops 5
  strict true
}
```

**Comment by francislavoie** [comment]
Right, those errors should be wrapped in `caddyhttp.Error(http.StatusForbidden, err)` then, so that status 403 is returned instead of 500.

https://github.com/kirsch33/realip/blob/e219301c6e5e7912cde4143ff02c27b8e40a8cbd/module.go#L137

Feel free to make a PR, I'm sure @kirsch33 would appreciate it 😄 

I think alternatively, you might be able to use `handle_errors` + `respond` to change the response https://caddyserver.com/docs/caddyfile/directives/handle_errors

**Comment by kirsch33** [comment]
Hey guys, I will look into this tonight and try to push an update out!

Appreciate the feedback and the help of @francislavoie

**Comment by francislavoie** [comment]
P.S. @kirsch33 don't forget to make an account on https://caddyserver.com/download and register your plugin so it shows up on the downloads page! It serves as the registry of Caddy plugins, and it'll make it easier to find for people who want to use it. Someone asked for the feature today on the forums 😄 https://caddy.community/t/restore-real-ip-to-logs/10911

**Comment by kirsch33** [comment]
@francislavoie Ive tried but for some reason I get an error! Not sure if its something in the code that it doesnt like or what. I posted this on the caddy forums but Matt never got back to me. The error I get is this:
```
Please include this error ID if reporting:
8e68a39b-1cfe-4a2d-ab2d-a652dba08e93
```

Also @kyori19 I didnt find time last night to address this but I will sometime before Christmas.

**Comment by mholt** [comment]
@kirsch33 The error is:

```
go get https:/github.com/kirsch33/realip@master: malformed module path "https:/github.com/kirsch33/realip": invalid char ':'
```

Make sure to provide the _module path_, not a URL.

**Comment by kirsch33** [comment]
@mholt easy enough! fixed and added. thanks for following up.

**Comment by kirsch33** [comment]
@kyori19  can you rebuild and reference the following commit in your build args:
```
9c8b5f86b90c3a5c81d81419820ee28646afa42c
```
and then let me know if it works for you?

i'm having issues re-creating your situation due to the way my server is configured, and figured it may be faster to have you guinea pig it.

**Comment by kyori19** [comment]
@kirsch33 I confirmed it works fine. Thanks for quick fix!
