### ISSUE TITLE
Add a note about the necessary 'order' option

### ISSUE THREAD

**Issue by dpantel** [kirsch33/realip#3]
Since Caddy2 does not know where to place this plugin it its order of execution, you have to explicitly tell it.  If you don't, Caddy will fail with the error:
> ... directive 'realip' is not ordered, so it cannot be used here

From Caddy documentation:
> You can override/customize this ordering by using the [`order` global option](https://caddyserver.com/docs/caddyfile/options#order) or the [`route` directive](https://caddyserver.com/docs/caddyfile/directives/route).

It would be very helpful to add this tidbit to the Readme and make some suggestions as to where in the order of things this plugin may be useful. Do it first? or do it before reverse-proxying? It's not clear.

**Comment by francislavoie** [comment]
I'd recommend `order realip first`.

**Comment by kirsch33** [comment]
yes! great idea that needs to happen. I will knock it out this evening.
