### ISSUE TITLE
Please update document

### ISSUE THREAD

**Issue by Saved1387** [kirsch33/realip#6]
I used a lot of search to find out the usage configuration of the plugin in Caddyfile
Finally found the usage method at the link below
https://github.com/common-creation/caddy-docker/blob/main/etc/sample.Caddyfile

**Comment by francislavoie** [comment]
Did you miss the example right in the README? https://github.com/kirsch33/realip#example

**Comment by Saved1387** [comment]
I am a novice,
This document is terrible and does not introduce a solution that can be used.
I only know in the test now that I need to add a copy
{order realip first} at the root,
Otherwise, just like https://github.com/kirsch33/realip/issues/3, I have not known my problems.



我是新手，
这份文档很糟糕，没有介绍一份能用的方案，
我现在的测试才知道，我需要添加一份
{ order realip first} 在根部，
不然就像 https://github.com/kirsch33/realip/issues/3 一样一直不知道自己的问题
